version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: nav-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nav
      MYSQL_USER: nav_user
      MYSQL_PASSWORD: nav_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Go 后端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nav-backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: nav
      PORT: 8080
      JWT_SECRET: your-secret-key-change-this
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: go run main.go

  # Vue 前端
  frontend:
    build:
      context: ./homepage
      dockerfile: Dockerfile
    container_name: nav-frontend
    environment:
      VITE_API_URL: http://localhost:8080/api
    ports:
      - "5173:5173"
    volumes:
      - ./homepage:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mysql_data:
